---
apiVersion: v1
kind: ConfigMap
metadata:
  name: petrosa-data-manager-config
  namespace: petrosa-apps
  labels:
    app: data-manager
    component: data-intelligence
    version: VERSION_PLACEHOLDER
data:
  # Environment
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  
  # NATS Configuration
  NATS_CONSUMER_SUBJECT: "binance.futures.websocket.data"
  NATS_CLIENT_NAME: "petrosa-data-manager-consumer"
  NATS_CONNECT_TIMEOUT: "10"
  NATS_MAX_RECONNECT_ATTEMPTS: "10"
  NATS_RECONNECT_TIME_WAIT: "2"
  
  # Feature Flags
  ENABLE_AUDITOR: "true"  # Enabled: now has leader election support
  ENABLE_BACKFILLER: "true"  # Enabled: required for auto-backfill to work
  ENABLE_ANALYTICS: "false"  # Disabled: runs without leader election, causes duplicate work
  ENABLE_API: "true"
  
  # Leader Election Configuration
  ENABLE_LEADER_ELECTION: "true"
  LEADER_ELECTION_HEARTBEAT_INTERVAL: "10"  # seconds
  LEADER_ELECTION_TIMEOUT: "30"  # seconds
  
  # Auto-Backfill Configuration
  ENABLE_AUTO_BACKFILL: "true"  # Enabled: automatically backfill detected gaps
  MIN_AUTO_BACKFILL_GAP: "3600"  # 1 hour in seconds
  MAX_AUTO_BACKFILL_JOBS: "5"
  
  # Duplicate Handling Configuration
  ENABLE_DUPLICATE_REMOVAL: "false"  # Disabled initially for conservative rollout
  DUPLICATE_RESOLUTION_STRATEGY: "keep_newest"  # keep_newest, keep_oldest, manual
  
  # Scheduling Configuration
  AUDIT_INTERVAL: "300"  # 5 minutes
  ANALYTICS_INTERVAL: "900"  # 15 minutes
  HEALTH_CHECK_INTERVAL: "60"  # 1 minute
  
  # API Configuration
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  API_WORKERS: "4"
  
  # Binance API Configuration
  BINANCE_API_BASE_URL: "https://api.binance.com"
  BINANCE_FAPI_BASE_URL: "https://fapi.binance.com"
  BINANCE_RATE_LIMIT: "1200"
  
  # Data Processing Configuration
  MAX_BATCH_SIZE: "1000"
  MAX_CONCURRENT_TASKS: "10"
  MESSAGE_QUEUE_SIZE: "10000"
  
  # Gap Detection Configuration
  GAP_TOLERANCE_SECONDS: "60"
  MIN_GAP_SIZE_SECONDS: "120"
  
  # Analytics Configuration
  DEFAULT_VOLATILITY_WINDOW: "30"
  DEFAULT_VOLUME_WINDOW: "24"
  DEFAULT_TREND_WINDOW: "20"
  
  # Health Check Configuration
  HEALTH_CHECK_PORT: "8080"
  METRICS_PORT: "9090"
  
  # OpenTelemetry Configuration
  OTEL_ENABLED: "true"
  OTEL_SERVICE_NAME: "petrosa-data-manager"
  
  # Supported trading pairs
  SUPPORTED_PAIRS: "BTCUSDT,ETHUSDT,BNBUSDT,ADAUSDT,SOLUSDT"
  
  # Logging Configuration
  LOG_REQUEST_DETAILS: "true"
  LOG_RESPONSE_DETAILS: "true"
  LOG_QUERY_DETAILS: "false"

